version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: node-testing
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    ports:
      - "80:3000"
      - "${APP_PORT:-8081}:80"
      - "${APP_PORT_VITE:-5173}:5173"
    extra_hosts:
      - docker-chatwoot.com:172.18.0.4
    networks:
      - node-testing-net
      - cte-with-vpn

networks:
  cte-with-vpn:
    external:
      name: ctdesarrollo-with-vpn
  node-testing-net:
